version: "3.9"
services:
app:
build: .
container_name: rltrader
restart: always
environment:
- API_KEY=${API_KEY}
- CORS_ORIGIN=${CORS_ORIGIN}
- PORT=8000
- MODEL_DIR=/data/models
- DB_PATH=/data/trades.sqlite3
volumes:
- ./data:/data
ports:
- "8000:8000"


# Optional: add Caddy for TLS and clean domain
# caddy:
# image: caddy:2
# restart: unless-stopped
# ports:
# - "80:80"
# - "443:443"
# volumes:
# - ./Caddyfile:/etc/caddy/Caddyfile
# - caddy_data:/data
# - caddy_config:/config


volumes:
caddy_data: {}
caddy_config: {}
